databases:
  - name: effortless
    databaseName: effortless
    user: effortless_user

services:
  - type: web
    name: effortlessaas
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase: effortless
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
