databases:
  - name: effortless
    databaseName: effortless
    user: effortless_user

services:
  - type: web
    name: effortlessaas
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DB_INTERNAL_URL
        fromDatabase:
          name: effortless
          property: postgres://effortless_user:wx0gNOvFDq2BPb84bBd5Pqp9rxc12Swk@dpg-cfun1ehmbjsj9alqd01g-a/effortless
      - key: RAILS_MASTER_KEY
        sync: false
